class AppRoutes{
  static const String SPLASH_SCREEN_ROUTE='SPLASH_SCREEN_ROUTE';
  static const String LOGIN_SCREEN_ROUTE='LOGIN_SCREEN_ROUTE';
  static const String CHANGE_PASSWORD_SCREEN_ROUTE='CHANGE_PASSWORD_SCREEN_ROUTE';
  static const String FORGET_PASSWORD_SCREEN_ROUTE='FORGET_PASSWORD_SCREEN_ROUTE';
  static const String CONFIRM_EMAIL_SCREEN_ROUTE='CONFIRM_EMAIL_SCREEN_ROUTE';
  static const String HOME_TABS_SCREEN_ROUTE='HOME_TABS_SCREEN_ROUTE';




}